-- ============================================================================
-- Vee platform — 0004: seed data
-- Ported verbatim from the original static site's PLAN_ITEMS / product
-- descriptions (js/i18n.js) plus the platform's feature-flag catalogue and
-- Vee's own hardware product line, so the rebuilt platform launches with
-- real, correct content rather than lorem ipsum.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- plans
-- ---------------------------------------------------------------------------
insert into plans (id, name, tagline, price_iqd, billing_cycle, features, max_locations, max_staff, sort_order, active) values (
  'vee_start', '{"en":"Vee Start","ar":"Vee Start","ku":"Vee Start"}'::jsonb, '{"en":"For small businesses that need a professional digital presence.","ar":"للأعمال الصغيرة التي تحتاج حضورًا رقميًا احترافيًا.","ku":"بۆ بزنسی بچووک کە پێویستی بە بوونی دیجیتاڵی پیشەیی هەیە."}'::jsonb, 10000, 'monthly', '{"en":["Vee Business Profile","Digital Menu","NFC setup","QR Code","Business logo and information","Arabic / English / Kurdish","WhatsApp, Instagram, Maps, Reviews","Call button","Basic menu management","Basic analytics","Mobile-optimized profile","Vee hosting"],"ar":["ملف Vee للأعمال","قائمة رقمية","إعداد NFC","رمز QR","شعار ومعلومات العمل","عربي / إنجليزي / كردي","واتساب وإنستغرام وخرائط وتقييمات","زر اتصال","إدارة أساسية للقائمة","تحليلات أساسية","ملف محسّن للهاتف","استضافة Vee"],"ku":["پرۆفایلی بزنسی Vee","مێنووی دیجیتاڵ","ڕێکخستنی NFC","کۆدی QR","لۆگۆ و زانیاری بزنس","عەرەبی / ئینگلیزی / کوردی","واتساپ، ئینستاگرام، ماپس، هەڵسەنگاندن","دوگمەی پەیوەندی","بەڕێوەبردنی سەرەتایی مێنوو","شیکاری سەرەتایی","پرۆفایلی گونجاو بۆ مۆبایل","هۆستینگی Vee"]}'::jsonb, 1, 1, 0, true
);
insert into plans (id, name, tagline, price_iqd, billing_cycle, features, max_locations, max_staff, sort_order, active) values (
  'vee_business', '{"en":"Vee Business","ar":"Vee Business","ku":"Vee Business"}'::jsonb, '{"en":"For restaurants, cafés and growing businesses.","ar":"للمطاعم والمقاهي والأعمال المتنامية.","ku":"بۆ چێشتخانە، کافێ و بزنسی گەشەسەندوو."}'::jsonb, 20000, 'monthly', '{"en":["Everything in Start, plus:","Advanced digital menu","Product images, descriptions & categories","Availability, featured & popular products","Offers & promotions","Add-ons & product options","WhatsApp ordering","Custom business links","Advanced analytics & interaction tracking","Customizable profile","Multiple languages","Priority support"],"ar":["كل ما في Start، بالإضافة إلى:","قائمة رقمية متقدمة","صور ووصف وفئات للمنتجات","التوفر والمنتجات المميزة والرائجة","عروض وترويجات","إضافات وخيارات المنتجات","طلب عبر واتساب","روابط عمل مخصصة","تحليلات متقدمة وتتبع التفاعل","ملف قابل للتخصيص","لغات متعددة","دعم ذو أولوية"],"ku":["هەموو ئەوەی لە Start، زیادی سەر:","مێنووی دیجیتاڵی پێشکەوتوو","وێنە، وەسف و بەشی بەرهەم","بەردەستبوون، بەرهەمی تایبەت و بەناوبانگ","ئۆفەر و پرۆمۆشن","زیادکراو و هەڵبژاردنی بەرهەم","داواکاری بە واتساپ","لینکی تایبەتی بزنس","شیکاری پێشکەوتوو و شوێنکەوتنی کارلێک","پرۆفایلی گۆڕاو","چەند زمانێک","پشتگیری ئەولەویەتدار"]}'::jsonb, 1, 3, 1, true
);
insert into plans (id, name, tagline, price_iqd, billing_cycle, features, max_locations, max_staff, sort_order, active) values (
  'vee_pro', '{"en":"Vee Pro","ar":"Vee Pro","ku":"Vee Pro"}'::jsonb, '{"en":"For businesses that want the complete Vee experience.","ar":"للأعمال التي تريد تجربة Vee الكاملة.","ku":"بۆ بزنسێک کە ئەزموونی تەواوی Vee دەوێت."}'::jsonb, 40000, 'monthly', '{"en":["Everything in Business, plus:","Online ordering","Table ordering (Table QR / NFC)","Multiple locations & multiple menus","Advanced analytics & customer behavior insights","Advanced promotions","Custom branding","Custom domain support","Multiple staff accounts & permissions","Priority support","Future Vee platform features"],"ar":["كل ما في Business، بالإضافة إلى:","طلب أونلاين","طلب من الطاولة (QR / NFC للطاولة)","فروع وقوائم متعددة","تحليلات متقدمة ورؤى سلوك العملاء","ترويجات متقدمة","علامة تجارية مخصصة","دعم نطاق مخصص","حسابات موظفين متعددة وصلاحيات","دعم ذو أولوية","ميزات Vee المستقبلية"],"ku":["هەموو ئەوەی لە Business، زیادی سەر:","داواکاری ئۆنلاین","داواکاری مێز (QR / NFC ی مێز)","چەند لق و چەند مێنوو","شیکاری پێشکەوتوو و تێگەیشتنی ڕەفتاری کڕیار","پرۆمۆشنی پێشکەوتوو","براندی تایبەت","پشتیوانی دۆمەینی تایبەت","چەند هەژماری کارمەند و مۆڵەت","پشتگیری ئەولەویەتدار","تایبەتمەندییە داهاتووەکانی Vee"]}'::jsonb, 5, 10, 2, true
);
insert into plans (id, name, tagline, price_iqd, billing_cycle, features, max_locations, max_staff, sort_order, active) values (
  'vee_custom', '{"en":"Vee Custom","ar":"Vee Custom","ku":"Vee Custom"}'::jsonb, '{"en":"Built around your business — hotels, restaurant groups, large cafés, retail companies, salons, clinics, multiple branches and corporate businesses.","ar":"مصممة حول عملك — فنادق، مجموعات مطاعم، مقاهي كبيرة، شركات تجزئة، صالونات، عيادات، فروع متعددة وشركات.","ku":"لەسەر بنەمای بزنسەکەت دروستکراوە — هۆتێل، گرووپی چێشتخانە، کافێی گەورە، کۆمپانیای فرۆشگا، سالۆن، کلینیک، چەند لق و بزنسی کۆمپانی."}'::jsonb, null, 'monthly', '{"en":["Multiple branches","Custom digital experience","Custom domain","Advanced integrations & API","Custom ordering system","Custom dashboard","Custom branding","Dedicated support","Enterprise analytics"],"ar":["فروع متعددة","تجربة رقمية مخصصة","نطاق مخصص","تكاملات متقدمة وAPI","نظام طلبات مخصص","لوحة تحكم مخصصة","علامة تجارية مخصصة","دعم مخصص","تحليلات للمؤسسات"],"ku":["چەند لق","ئەزموونی دیجیتاڵی تایبەت","دۆمەینی تایبەت","یەکخستنی پێشکەوتوو و API","سیستەمی داواکاری تایبەت","داشبۆردی تایبەت","براندی تایبەت","پشتگیری تایبەتمەند","شیکاری کۆمپانی"]}'::jsonb, 999, 999, 3, true
);

-- ---------------------------------------------------------------------------
-- feature_flags
-- ---------------------------------------------------------------------------
insert into feature_flags (key, label, description, scope, default_value) values ('public_profiles', 'Public business profiles', 'Business profile page at vee.iq/:username', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('digital_menus', 'Digital menus', 'The digital menu system at vee.iq/:username/menu', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('whatsapp_ordering', 'WhatsApp ordering', 'Cart totals formatted into a WhatsApp deep link order', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('online_ordering', 'Online ordering', 'Orders persisted and managed from the dashboard', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('table_ordering', 'Table ordering', 'Per-table QR/NFC ordering with a table number', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('reservations', 'Reservations', 'Reservation link/button on the business profile', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('google_reviews', 'Google Reviews', 'One-tap Google Review link on the profile and NFC cards', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('analytics', 'Analytics', 'Profile/menu/order analytics in the business dashboard', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('nfc_activation', 'NFC activation', 'Ability to activate/reassign physical NFC devices', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('qr_codes', 'QR codes', 'QR code generation for profiles and menus', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('product_catalogue', 'Product catalogue', 'The public Vee hardware product catalogue', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('custom_links', 'Custom links', 'Business owners can add custom links beyond the fixed set', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('image_uploads', 'Image uploads', 'Logo/cover/menu-item image uploads to storage', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('multiple_locations', 'Multiple locations', 'A business can manage more than one location', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('staff_access', 'Staff access', 'Business owners can invite staff with scoped permissions', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('offers_promotions', 'Offers & promotions', 'Promotional banner/offer text on the profile', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('contact_forms', 'Contact forms', 'Public sales enquiry / contact form', 'global', true);
insert into feature_flags (key, label, description, scope, default_value) values ('subscription_plans', 'Subscription plans', 'Plan selection and billing status display', 'global', true);

-- ---------------------------------------------------------------------------
-- catalogue_products
-- ---------------------------------------------------------------------------
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-NFC-CUSTOM', 'nfc_card', '{"en":"Vee Custom NFC Card","ar":"بطاقة Vee NFC المخصصة","ku":"کارتی Vee NFC ی تایبەت"}'::jsonb, '{"en":"A custom NFC card carrying your business name and logo. One tap opens your chosen destination — your profile, links, menu, contact details, or anywhere else you decide to send customers.","ar":"بطاقة NFC مخصصة تحمل اسم عملك وشعارك. لمسة واحدة تفتح الوجهة التي تختارها — ملفك، روابطك، قائمتك، بيانات التواصل، أو أي وجهة أخرى تحددها.","ku":"کارتێکی NFC ی تایبەت کە ناو و لۆگۆی بزنسەکەت لەسەریەتی. یەک دەستلێدان ئەو ناونیشانە دەکاتەوە کە هەڵتبژاردووە — پرۆفایل، لینک، مێنوو، زانیاری پەیوەندی یان هەر شوێنێکی تر."}'::jsonb, '{"en":["Printed with your business name & logo","Opens any destination you choose","Reprogrammable at any time from your dashboard","Available in black and white"],"ar":["مطبوعة باسم وشعار عملك","تفتح أي وجهة تختارها","قابلة لإعادة البرمجة في أي وقت من لوحة التحكم","متوفرة باللونين الأسود والأبيض"],"ku":["چاپکراو بە ناو و لۆگۆی بزنسەکەت","هەر ناونیشانێک کە هەڵتبژێریت دەکاتەوە","لە هەر کاتێک دەتوانرێت لە داشبۆردەوە دووبارە بەرنامەسازی بکرێت","بە ڕەنگی ڕەش و سپی بەردەستە"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-nfc-card-custom.svg"]'::jsonb, '["black","white"]'::jsonb, 'published', 0, true, '{"en":"Vee Custom NFC Card","ar":"بطاقة Vee NFC المخصصة","ku":"کارتی Vee NFC ی تایبەت"}'::jsonb, '{"en":"A custom NFC card carrying your business name and logo. One tap opens your chosen destination — your profile, links, menu, contact details, or anywhere els","ar":"بطاقة NFC مخصصة تحمل اسم عملك وشعارك. لمسة واحدة تفتح الوجهة التي تختارها — ملفك، روابطك، قائمتك، بيانات التواصل، أو أي وجهة أخرى تحددها.","ku":"کارتێکی NFC ی تایبەت کە ناو و لۆگۆی بزنسەکەت لەسەریەتی. یەک دەستلێدان ئەو ناونیشانە دەکاتەوە کە هەڵتبژاردووە — پرۆفایل، لینک، مێنوو، زانیاری پەیوەندی یان ه"}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-NFC-GREVIEW', 'nfc_card', '{"en":"Vee Google Review NFC Card","ar":"بطاقة Vee NFC لتقييمات غوغل","ku":"کارتی Vee NFC بۆ هەڵسەنگاندنی گووگڵ"}'::jsonb, '{"en":"Send customers straight to your Google Review page with one tap — the fastest way to turn a happy customer into a 5-star review, right at the table or counter.","ar":"أرسل عملاءك مباشرة إلى صفحة تقييمك على غوغل بلمسة واحدة — أسرع طريقة لتحويل عميل راضٍ إلى تقييم خمس نجوم، مباشرة عند الطاولة أو الكاونتر.","ku":"کڕیارەکانت بە یەک دەستلێدان ڕاستەوخۆ بنێرە بۆ پەڕەی هەڵسەنگاندنی گووگڵ — خێراترین ڕێگا بۆ گۆڕینی کڕیارێکی دڵخۆش بۆ هەڵسەنگاندنی 5 ئەستێرە."}'::jsonb, '{"en":["One tap to your Google Review page","No app required for the customer","Boosts review volume and rating","Available in black and white"],"ar":["لمسة واحدة إلى صفحة تقييمك على غوغل","لا حاجة لتطبيق من طرف العميل","يزيد عدد التقييمات والتقييم العام","متوفرة باللونين الأسود والأبيض"],"ku":["یەک دەستلێدان بۆ پەڕەی هەڵسەنگاندنی گووگڵ","پێویست بە ئەپ ناکات بۆ کڕیار","ژمارە و ئاستی هەڵسەنگاندن بەرز دەکاتەوە","بە ڕەنگی ڕەش و سپی بەردەستە"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-nfc-card-greview.svg"]'::jsonb, '["black","white"]'::jsonb, 'published', 1, true, '{"en":"Vee Google Review NFC Card","ar":"بطاقة Vee NFC لتقييمات غوغل","ku":"کارتی Vee NFC بۆ هەڵسەنگاندنی گووگڵ"}'::jsonb, '{"en":"Send customers straight to your Google Review page with one tap — the fastest way to turn a happy customer into a 5-star review, right at the table or coun","ar":"أرسل عملاءك مباشرة إلى صفحة تقييمك على غوغل بلمسة واحدة — أسرع طريقة لتحويل عميل راضٍ إلى تقييم خمس نجوم، مباشرة عند الطاولة أو الكاونتر.","ku":"کڕیارەکانت بە یەک دەستلێدان ڕاستەوخۆ بنێرە بۆ پەڕەی هەڵسەنگاندنی گووگڵ — خێراترین ڕێگا بۆ گۆڕینی کڕیارێکی دڵخۆش بۆ هەڵسەنگاندنی 5 ئەستێرە."}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-NFC-MIFARE', 'nfc_card', '{"en":"Vee MIFARE NFC Card","ar":"بطاقة Vee MIFARE NFC","ku":"کارتی Vee MIFARE NFC"}'::jsonb, '{"en":"A MIFARE-standard NFC card for businesses that need it for access, loyalty, or other MIFARE-compatible applications, alongside your Vee digital experience.","ar":"بطاقة NFC بمعيار MIFARE للأعمال التي تحتاجها للدخول، برامج الولاء، أو تطبيقات أخرى متوافقة مع MIFARE، إلى جانب تجربة Vee الرقمية.","ku":"کارتێکی NFC ی ستانداردی MIFARE بۆ بزنسەکانێک کە پێویستیان پێیەتی بۆ چوونەژوورەوە، پرۆگرامی دڵسۆزی، یان بەکارهێنانی تری گونجاو لەگەڵ MIFARE، لەگەڵ ئەزموونی دیجیتاڵی Vee."}'::jsonb, '{"en":["MIFARE-standard chip","Compatible with existing access/loyalty systems","Carries your Vee profile link","Available in black and white"],"ar":["شريحة بمعيار MIFARE","متوافقة مع أنظمة الدخول والولاء الحالية","تحمل رابط ملفك على Vee","متوفرة باللونين الأسود والأبيض"],"ku":["چیپی ستانداردی MIFARE","گونجاوە لەگەڵ سیستەمی چوونەژوورەوە و دڵسۆزیی ئێستا","لینکی پرۆفایلی Vee ـت هەڵدەگرێت","بە ڕەنگی ڕەش و سپی بەردەستە"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-nfc-card-mifare.svg"]'::jsonb, '["black","white"]'::jsonb, 'published', 2, false, '{"en":"Vee MIFARE NFC Card","ar":"بطاقة Vee MIFARE NFC","ku":"کارتی Vee MIFARE NFC"}'::jsonb, '{"en":"A MIFARE-standard NFC card for businesses that need it for access, loyalty, or other MIFARE-compatible applications, alongside your Vee digital experience.","ar":"بطاقة NFC بمعيار MIFARE للأعمال التي تحتاجها للدخول، برامج الولاء، أو تطبيقات أخرى متوافقة مع MIFARE، إلى جانب تجربة Vee الرقمية.","ku":"کارتێکی NFC ی ستانداردی MIFARE بۆ بزنسەکانێک کە پێویستیان پێیەتی بۆ چوونەژوورەوە، پرۆگرامی دڵسۆزی، یان بەکارهێنانی تری گونجاو لەگەڵ MIFARE، لەگەڵ ئەزموونی "}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-ACRYLIC-STAND', 'acrylic', '{"en":"Vee Acrylic NFC Stand","ar":"حامل Vee الأكريليك NFC","ku":"ستاندی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"A premium acrylic table stand for restaurants and cafés. One tap opens your digital menu or business profile, and can include a table number for table-based ordering.","ar":"حامل طاولة أكريليك فاخر للمطاعم والمقاهي. لمسة واحدة تفتح قائمتك الرقمية أو ملف عملك، ويمكن أن يتضمن رقم الطاولة للطلب من الطاولة.","ku":"ستاندێکی مێزی ئەکریلیکی پرێمیۆم بۆ چێشتخانە و کافێکان. یەک دەستلێدان مێنووی دیجیتاڵ یان پرۆفایلی بزنسەکەت دەکاتەوە، و دەتوانێت ژمارەی مێز لەخۆبگرێت بۆ داواکاری لەسەر مێز."}'::jsonb, '{"en":["Premium clear acrylic construction","Opens the digital menu or profile","Optional table number for table ordering","Sits neatly on any table or counter"],"ar":["هيكل أكريليك شفاف فاخر","يفتح القائمة الرقمية أو الملف","رقم طاولة اختياري للطلب من الطاولة","يوضع بأناقة على أي طاولة أو كاونتر"],"ku":["دروستکراو لە ئەکریلیکی ڕوونی پرێمیۆم","مێنووی دیجیتاڵ یان پرۆفایل دەکاتەوە","ژمارەی مێزی هەڵبژاردەیی بۆ داواکاریی مێز","بە جوانی لەسەر هەر مێز یان کاونتێرێک دادەنرێت"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-acrylic-stand.svg"]'::jsonb, '["clear"]'::jsonb, 'published', 3, true, '{"en":"Vee Acrylic NFC Stand","ar":"حامل Vee الأكريليك NFC","ku":"ستاندی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"A premium acrylic table stand for restaurants and cafés. One tap opens your digital menu or business profile, and can include a table number for table-base","ar":"حامل طاولة أكريليك فاخر للمطاعم والمقاهي. لمسة واحدة تفتح قائمتك الرقمية أو ملف عملك، ويمكن أن يتضمن رقم الطاولة للطلب من الطاولة.","ku":"ستاندێکی مێزی ئەکریلیکی پرێمیۆم بۆ چێشتخانە و کافێکان. یەک دەستلێدان مێنووی دیجیتاڵ یان پرۆفایلی بزنسەکەت دەکاتەوە، و دەتوانێت ژمارەی مێز لەخۆبگرێت بۆ داوا"}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-ACRYLIC-FLAT', 'acrylic', '{"en":"Vee Acrylic NFC Flat Piece","ar":"قطعة Vee الأكريليك المسطحة NFC","ku":"پارچەی تەختی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"A flat acrylic NFC and QR piece that attaches to a table. Opens your digital menu by tap or scan, and can include a table number.","ar":"قطعة أكريليك مسطحة بتقنية NFC و QR تُثبَّت على الطاولة. تفتح قائمتك الرقمية باللمس أو المسح، ويمكن أن تتضمن رقم الطاولة.","ku":"پارچەیەکی تەختی ئەکریلیکی NFC و QR کە لەسەر مێز دادەنرێت. مێنووی دیجیتاڵ بە دەستلێدان یان سکان دەکاتەوە، و دەتوانێت ژمارەی مێز لەخۆبگرێت."}'::jsonb, '{"en":["Low-profile flat design","Both NFC tap and QR scan supported","Opens the digital menu directly","Optional table number"],"ar":["تصميم مسطح منخفض الارتفاع","يدعم اللمس NFC والمسح QR معًا","يفتح القائمة الرقمية مباشرة","رقم طاولة اختياري"],"ku":["دیزاینی تەختی نزم","پشتگیری هەردوو دەستلێدانی NFC و سکانی QR","ڕاستەوخۆ مێنووی دیجیتاڵ دەکاتەوە","ژمارەی مێزی هەڵبژاردەیی"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-flat-tag.svg"]'::jsonb, '["clear"]'::jsonb, 'published', 4, false, '{"en":"Vee Acrylic NFC Flat Piece","ar":"قطعة Vee الأكريليك المسطحة NFC","ku":"پارچەی تەختی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"A flat acrylic NFC and QR piece that attaches to a table. Opens your digital menu by tap or scan, and can include a table number.","ar":"قطعة أكريليك مسطحة بتقنية NFC و QR تُثبَّت على الطاولة. تفتح قائمتك الرقمية باللمس أو المسح، ويمكن أن تتضمن رقم الطاولة.","ku":"پارچەیەکی تەختی ئەکریلیکی NFC و QR کە لەسەر مێز دادەنرێت. مێنووی دیجیتاڵ بە دەستلێدان یان سکان دەکاتەوە، و دەتوانێت ژمارەی مێز لەخۆبگرێت."}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-ACRYLIC-TISSUE', 'acrylic', '{"en":"Vee Acrylic NFC Tissue Box","ar":"علبة مناديل Vee الأكريليك NFC","ku":"قوتوی مەندیلی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"An NFC-enabled tissue-box holder for restaurant tables — a fixture that''s already on the table, doing double duty as your digital menu access point.","ar":"حامل علبة مناديل مزود بتقنية NFC لطاولات المطاعم — قطعة موجودة أصلاً على الطاولة، تؤدي دورًا مزدوجًا كنقطة وصول لقائمتك الرقمية.","ku":"گرتووی قوتوی مەندیلی دەستکراو بە NFC بۆ مێزی چێشتخانەکان — پارچەیەک کە پێشتر لەسەر مێزە، دوو ئەرکی هەیە وەک خاڵی دەستگەیشتن بۆ مێنووی دیجیتاڵ."}'::jsonb, '{"en":["Doubles as a tissue-box holder","NFC tap opens the digital menu","Blends naturally into the table setting","Durable acrylic construction"],"ar":["يعمل كحامل لعلبة المناديل أيضًا","لمسة NFC تفتح القائمة الرقمية","يندمج بشكل طبيعي مع إعداد الطاولة","هيكل أكريليك متين"],"ku":["هەروەها وەک گرتووی قوتوی مەندیل کاردەکات","دەستلێدانی NFC مێنووی دیجیتاڵ دەکاتەوە","بە سروشتی لەگەڵ ڕێکخستنی مێز دەگونجێت","دروستکراو لە ئەکریلیکی بەرگری"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-tissue-box.svg"]'::jsonb, '["clear"]'::jsonb, 'published', 5, false, '{"en":"Vee Acrylic NFC Tissue Box","ar":"علبة مناديل Vee الأكريليك NFC","ku":"قوتوی مەندیلی ئەکریلیکی Vee NFC"}'::jsonb, '{"en":"An NFC-enabled tissue-box holder for restaurant tables — a fixture that''s already on the table, doing double duty as your digital menu access point.","ar":"حامل علبة مناديل مزود بتقنية NFC لطاولات المطاعم — قطعة موجودة أصلاً على الطاولة، تؤدي دورًا مزدوجًا كنقطة وصول لقائمتك الرقمية.","ku":"گرتووی قوتوی مەندیلی دەستکراو بە NFC بۆ مێزی چێشتخانەکان — پارچەیەک کە پێشتر لەسەر مێزە، دوو ئەرکی هەیە وەک خاڵی دەستگەیشتن بۆ مێنووی دیجیتاڵ."}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-TENT-DOUBLE', 'acrylic', '{"en":"Vee Double-Sided Tent NFC Stand","ar":"حامل خيمة Vee NFC ثنائي الجانب","ku":"ستاندی چادری دوو لای Vee NFC"}'::jsonb, '{"en":"A double-sided acrylic table tent with print and NFC access on both faces, so customers can reach your menu from either side of the table.","ar":"خيمة طاولة أكريليك ثنائية الجانب بطباعة ووصول NFC على كلا الوجهين، بحيث يمكن للعملاء الوصول إلى قائمتك من أي جانب من الطاولة.","ku":"چادرێکی مێزی ئەکریلیکی دوو لای بە چاپ و دەستگەیشتنی NFC لەسەر هەردوو ڕوو، تاکو کڕیار بتوانن لە هەردوو لای مێزەوە مێنووەکەت بدۆزنەوە."}'::jsonb, '{"en":["Print + NFC on both faces","Readable and tappable from either side of the table","Freestanding acrylic tent design","Ideal for two-sided or booth seating"],"ar":["طباعة + NFC على كلا الوجهين","قابلة للقراءة واللمس من أي جانب من الطاولة","تصميم خيمة أكريليك قائم بذاته","مثالية للجلوس ثنائي الجانب أو المقصورات"],"ku":["چاپ + NFC لەسەر هەردوو ڕوو","لە هەردوو لای مێزەوە دەخوێندرێتەوە و دەستی لێدەدرێت","دیزاینی چادری ئەکریلیکی سەربەخۆ","گونجاوە بۆ دانیشتنی دوو لای یان بۆکس"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-tent-double.svg"]'::jsonb, '["clear"]'::jsonb, 'published', 6, true, '{"en":"Vee Double-Sided Tent NFC Stand","ar":"حامل خيمة Vee NFC ثنائي الجانب","ku":"ستاندی چادری دوو لای Vee NFC"}'::jsonb, '{"en":"A double-sided acrylic table tent with print and NFC access on both faces, so customers can reach your menu from either side of the table.","ar":"خيمة طاولة أكريليك ثنائية الجانب بطباعة ووصول NFC على كلا الوجهين، بحيث يمكن للعملاء الوصول إلى قائمتك من أي جانب من الطاولة.","ku":"چادرێکی مێزی ئەکریلیکی دوو لای بە چاپ و دەستگەیشتنی NFC لەسەر هەردوو ڕوو، تاکو کڕیار بتوانن لە هەردوو لای مێزەوە مێنووەکەت بدۆزنەوە."}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, specifications, price_iqd, request_quote, images, colors, status, sort_order, featured, seo_title, seo_description, cta_type) values (
  'VEE-STEEL-STAND', 'steel', '{"en":"Vee Steel NFC Stand","ar":"حامل Vee الفولاذي NFC","ku":"ستاندی پۆڵایینی Vee NFC"}'::jsonb, '{"en":"A premium stainless-steel table stand for restaurants and cafés that want their NFC access point to match a premium interior.","ar":"حامل طاولة فولاذي فاخر للمطاعم والمقاهي التي تريد أن تتماشى نقطة وصول NFC مع ديكور داخلي راقٍ.","ku":"ستاندێکی مێزی پۆڵایینی زەنگنەگری پرێمیۆم بۆ چێشتخانە و کافێکانێک کە دەیانەوێت خاڵی دەستگەیشتنی NFC یان لەگەڵ دیزاینی ناوخۆیی پرێمیۆم بگونجێت."}'::jsonb, '{"en":["Brushed stainless-steel construction","Opens the digital menu or profile","Weighted, tip-resistant base","Premium look for premium venues"],"ar":["هيكل فولاذي مصقول","يفتح القائمة الرقمية أو الملف","قاعدة موزونة مقاومة للانقلاب","مظهر فاخر للأماكن الراقية"],"ku":["دروستکراو لە پۆڵایینی زەنگنەگری بریسکاوە","مێنووی دیجیتاڵ یان پرۆفایل دەکاتەوە","بنکەیەکی قورس و بەرگری لە کەوتن","ڕواڵەتێکی پرێمیۆم بۆ شوێنی پرێمیۆم"]}'::jsonb, '{}'::jsonb, null, true, '["/brand/product-steel-stand.svg"]'::jsonb, '["steel"]'::jsonb, 'published', 7, true, '{"en":"Vee Steel NFC Stand","ar":"حامل Vee الفولاذي NFC","ku":"ستاندی پۆڵایینی Vee NFC"}'::jsonb, '{"en":"A premium stainless-steel table stand for restaurants and cafés that want their NFC access point to match a premium interior.","ar":"حامل طاولة فولاذي فاخر للمطاعم والمقاهي التي تريد أن تتماشى نقطة وصول NFC مع ديكور داخلي راقٍ.","ku":"ستاندێکی مێزی پۆڵایینی زەنگنەگری پرێمیۆم بۆ چێشتخانە و کافێکانێک کە دەیانەوێت خاڵی دەستگەیشتنی NFC یان لەگەڵ دیزاینی ناوخۆیی پرێمیۆم بگونجێت."}'::jsonb, 'enquire'
);
insert into catalogue_products (sku, category, name, description, features, price_iqd, request_quote, images, colors, status, sort_order, featured, cta_type) values (
  'VEE-CUSTOM-SOLUTION', 'custom', '{"en":"Request a Custom Solution","ar":"اطلب حلاً مخصصًا","ku":"داواکاری چارەسەرێکی تایبەت بکە"}'::jsonb, '{"en":"Need a custom NFC design, a bulk order, or something not listed above? Tell us what you need and the Vee team will design it with you.","ar":"هل تحتاج تصميم NFC مخصص، طلبًا بالجملة، أو شيئًا غير مدرج أعلاه؟ أخبرنا بما تحتاجه وسيصممه فريق Vee معك.","ku":"پێویستت بە دیزاینی تایبەتی NFC، داواکاری کۆمەڵ، یان شتێکی تر هەیە کە لە سەرەوە ئاماژەی پێنەکراوە؟ پێمان بڵێ چیت پێویستە و تیمی Vee لەگەڵت دیزاینی دەکات."}'::jsonb, '["Custom design & branding","Bulk / wholesale pricing","Dedicated account manager"]'::jsonb, null, true, '["/brand/product-custom.svg"]'::jsonb, '[]'::jsonb, 'published', 8, false, 'quote'
);
