-- =====================================================================
-- 0010_cms_seed.sql
-- =====================================================================
-- Seeds the CMS tables extended in 0009 with the site's REAL current
-- content (mechanically extracted from lib/i18n/dictionaries/content.json
-- and the hardcoded header/footer link arrays), so turning on the new
-- DB-driven read paths does not change anything a visitor sees -- Super
-- Admin now has a live, populated screen to edit going forward instead of
-- landing on an empty CMS.
-- =====================================================================

-- Homepage section visibility + order (text itself stays translation-driven;
-- these rows only control whether a section renders and in what order).
insert into site_content (key, type, content, visible, sort_order) values ('homepage.hero', 'section', '{}'::jsonb, true, 0) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.explain', 'section', '{}'::jsonb, true, 1) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.why', 'section', '{}'::jsonb, true, 2) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.products', 'section', '{}'::jsonb, true, 3) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.how', 'section', '{}'::jsonb, true, 4) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.plans', 'section', '{}'::jsonb, true, 5) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.faq', 'section', '{}'::jsonb, true, 6) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('homepage.contact', 'section', '{}'::jsonb, true, 7) on conflict (key) do nothing;

-- FAQ items (migrated from content.json FAQ_ITEMS)
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.0', 'faq', '{"q": {"en": "What is Vee?", "ar": "ما هي Vee؟", "ku": "Vee چییە؟"}, "a": {"en": "Vee is a digital customer-experience platform for businesses in Iraq. A physical NFC/QR product connects customers to your Vee business profile — your menu, ordering, WhatsApp, Instagram, reviews, location and offers, all in one place.", "ar": "Vee منصة رقمية لتجربة العملاء للأعمال في العراق. يربط منتج NFC/QR المادي عملاءك بملف عملك على Vee — قائمتك وطلباتك وواتساب وإنستغرام وتقييماتك وموقعك وعروضك، كلها في مكان واحد.", "ku": "Vee پلاتفۆرمێکی دیجیتاڵی ئەزموونی کڕیارە بۆ بزنسەکان لە عێراق. بەرهەمێکی جەستەیی NFC/QR کڕیارەکانت بە پرۆفایلی بزنسی Veeت دەبەستێتەوە — مێنوو، داواکاری، واتساپ، ئینستاگرام، هەڵسەنگاندن، شوێن و ئۆفەرەکانت، هەموو لە یەک شوێن."}}'::jsonb, true, 0) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.1', 'faq', '{"q": {"en": "How does Vee NFC work?", "ar": "كيف يعمل NFC في Vee؟", "ku": "NFCی Vee چۆن کاردەکات؟"}, "a": {"en": "A customer taps their phone on the Vee product. Their phone opens your Vee business profile instantly, in their browser — no app needed.", "ar": "يلمس العميل هاتفه على منتج Vee. يفتح هاتفه ملف عملك على Vee فورًا في المتصفح — دون الحاجة لأي تطبيق.", "ku": "کڕیار مۆبایلەکەی لەسەر بەرهەمی Vee دادەنێت. مۆبایلەکەی دەستبەجێ پرۆفایلی بزنسی Veeت لە وێبگەڕدا دەکاتەوە — بێ پێویستی بە هیچ ئەپێک."}}'::jsonb, true, 1) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.2', 'faq', '{"q": {"en": "Does NFC work on every phone?", "ar": "هل يعمل NFC على كل الهواتف؟", "ku": "ئایا NFC لەسەر هەموو مۆبایلێک کاردەکات؟"}, "a": {"en": "Most modern smartphones support NFC. For the few that don''t, every Vee product also carries a QR code as a backup — same result, one extra second.", "ar": "تدعم معظم الهواتف الذكية الحديثة NFC. بالنسبة للقلة التي لا تدعمه، يحمل كل منتج Vee أيضًا رمز QR احتياطي — نفس النتيجة، بثانية إضافية واحدة فقط.", "ku": "زۆربەی مۆبایلە زیرەکە نوێیەکان پشتیوانی NFC دەکەن. بۆ ئەوانەی پشتیوانی ناکەن، هەر بەرهەمێکی Vee کۆدی QR ی پاڵپشتیشی هەیە — هەمان ئەنجام، بە یەک چرکەی زیادە."}}'::jsonb, true, 2) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.3', 'faq', '{"q": {"en": "Can I change my menu after receiving the NFC product?", "ar": "هل يمكنني تغيير قائمتي بعد استلام منتج NFC؟", "ku": "دەتوانم مێنووەکەم بگۆڕم دوای وەرگرتنی بەرهەمی NFC؟"}, "a": {"en": "Yes. The NFC/QR always points to your Vee business profile, not directly to a fixed menu — so you can update your menu, links or offers anytime without ever replacing the physical product.", "ar": "نعم. يشير NFC/QR دائمًا إلى ملف عملك على Vee، وليس مباشرة إلى قائمة ثابتة — لذا يمكنك تحديث قائمتك أو روابطك أو عروضك في أي وقت دون استبدال المنتج المادي أبدًا.", "ku": "بەڵێ. NFC/QR هەمیشە ئاماژە بە پرۆفایلی بزنسی Veeت دەکات، نەک ڕاستەوخۆ بۆ مێنوویەکی جێگیر — بۆیە دەتوانیت مێنوو، لینک یان ئۆفەرەکانت لە هەر کاتێک نوێ بکەیتەوە بێ ئەوەی بەرهەمە جەستەییەکە بگۆڕیت."}}'::jsonb, true, 3) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.4', 'faq', '{"q": {"en": "Can I change my Instagram or WhatsApp later?", "ar": "هل يمكنني تغيير إنستغرام أو واتساب لاحقًا؟", "ku": "دەتوانم دواتر ئینستاگرام یان واتسابم بگۆڕم؟"}, "a": {"en": "Yes — every link on your profile can be edited, reordered or disabled anytime from your Vee dashboard.", "ar": "نعم — يمكن تعديل أي رابط في ملفك أو إعادة ترتيبه أو تعطيله في أي وقت من لوحة تحكم Vee.", "ku": "بەڵێ — هەر لینکێک لە پرۆفایلەکەت دەتوانرێت لە هەر کاتێک لە داشبۆردی Veeوە دەستکاری بکرێت، ڕیز بکرێتەوە یان ناچالاک بکرێت."}}'::jsonb, true, 4) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.5', 'faq', '{"q": {"en": "Do I need an app?", "ar": "هل أحتاج إلى تطبيق؟", "ku": "ئایا پێویستم بە ئەپ هەیە؟"}, "a": {"en": "No. Customers access Vee entirely through their browser — no download, no install.", "ar": "لا. يصل العملاء إلى Vee بالكامل عبر المتصفح — بلا تنزيل وبلا تثبيت.", "ku": "نەخێر. کڕیارەکان بە تەواوی لە ڕێگەی وێبگەڕەوە دەگەنە Vee — بێ داگرتن و بێ دامەزراندن."}}'::jsonb, true, 5) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.6', 'faq', '{"q": {"en": "Can I use Vee for more than a restaurant?", "ar": "هل يمكنني استخدام Vee لغير المطاعم؟", "ku": "دەتوانم Vee بۆ زیاتر لە چێشتخانە بەکاربهێنم؟"}, "a": {"en": "Yes — salons, hotels, retail, clinics, gyms, services and personal brands all use Vee the same way.", "ar": "نعم — الصالونات والفنادق والمتاجر والعيادات والصالات الرياضية والخدمات والعلامات الشخصية كلها تستخدم Vee بنفس الطريقة.", "ku": "بەڵێ — سالۆن، هۆتێل، فرۆشگا، کلینیک، یانەی وەرزشی، خزمەتگوزاری و براندی کەسی هەموویان بە هەمان شێوە Vee بەکاردەهێنن."}}'::jsonb, true, 6) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.7', 'faq', '{"q": {"en": "Can I have multiple branches?", "ar": "هل يمكنني إضافة فروع متعددة؟", "ku": "دەتوانم چەند لقم هەبێت؟"}, "a": {"en": "Depending on your plan. Vee Pro and Vee Custom support multiple locations and multiple menus.", "ar": "بحسب خطتك. تدعم خطتا Vee Pro وVee Custom الفروع والقوائم المتعددة.", "ku": "بەپێی پلانەکەت. Vee Pro و Vee Custom پشتیوانی چەند لق و چەند مێنوو دەکەن."}}'::jsonb, true, 7) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.8', 'faq', '{"q": {"en": "Can customers order through Vee?", "ar": "هل يمكن للعملاء الطلب عبر Vee؟", "ku": "ئایا کڕیاران دەتوانن لە ڕێگەی Veeوە داوا بکەن؟"}, "a": {"en": "Depending on the ordering mode and plan you choose: menu-only, WhatsApp ordering, online ordering or table ordering.", "ar": "بحسب وضع الطلب والخطة التي تختارها: تصفح القائمة فقط، الطلب عبر واتساب، الطلب أونلاين، أو الطلب من الطاولة.", "ku": "بەپێی دۆخی داواکاری و پلانەکەی هەڵدەبژێریت: تەنها مێنوو، داواکاری بە واتساپ، داواکاری ئۆنلاین یان داواکاری مێز."}}'::jsonb, true, 8) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.9', 'faq', '{"q": {"en": "Does Vee support Arabic and Kurdish?", "ar": "هل تدعم Vee العربية والكردية؟", "ku": "ئایا Vee پشتیوانی عەرەبی و کوردی دەکات؟"}, "a": {"en": "Yes — Vee fully supports English, Arabic and Kurdish, with correct right-to-left layout for Arabic and Kurdish.", "ar": "نعم — تدعم Vee بالكامل الإنجليزية والعربية والكردية، مع تخطيط صحيح من اليمين لليسار للعربية والكردية.", "ku": "بەڵێ — Vee بە تەواوی پشتیوانی ئینگلیزی، عەرەبی و کوردی دەکات، لەگەڵ ڕیزبەندی ڕاست بۆ چەپی ڕاست بۆ عەرەبی و کوردی."}}'::jsonb, true, 9) on conflict (key) do nothing;
insert into site_content (key, type, content, visible, sort_order) values ('faq.item.10', 'faq', '{"q": {"en": "How do I get started?", "ar": "كيف أبدأ؟", "ku": "چۆن دەست پێبکەم؟"}, "a": {"en": "Choose a plan above, or contact Vee directly — we''ll set up your profile, menu and NFC/QR together.", "ar": "اختر خطة أعلاه، أو تواصل مع Vee مباشرة — سنُعدّ ملفك وقائمتك وNFC/QR معًا.", "ku": "پلانێک لە سەرەوە هەڵبژێرە، یان ڕاستەوخۆ پەیوەندی بە Veeوە بکە — پرۆفایل، مێنوو و NFC/QR ت پێکەوە ڕێکدەخەین."}}'::jsonb, true, 10) on conflict (key) do nothing;

-- Primary header navigation
insert into nav_menu_items (label, url, placement, access_rule, location, visible, sort_order) values ('{"en": "Home", "ar": "الرئيسية", "ku": "سەرەکی"}'::jsonb, '/', 'both', 'public', 'header', true, 0);
insert into nav_menu_items (label, url, placement, access_rule, location, visible, sort_order) values ('{"en": "Products", "ar": "المنتجات", "ku": "بەرهەمەکان"}'::jsonb, '/products', 'both', 'public', 'header', true, 1);
insert into nav_menu_items (label, url, placement, access_rule, location, visible, sort_order) values ('{"en": "How It Works", "ar": "كيف يعمل", "ku": "چۆن کاردەکات"}'::jsonb, '/#how', 'both', 'public', 'header', true, 2);
insert into nav_menu_items (label, url, placement, access_rule, location, visible, sort_order) values ('{"en": "Plans", "ar": "الخطط", "ku": "پلانەکان"}'::jsonb, '/#plans', 'both', 'public', 'header', true, 3);
insert into nav_menu_items (label, url, placement, access_rule, location, visible, sort_order) values ('{"en": "Contact", "ar": "تواصل معنا", "ku": "پەیوەندی"}'::jsonb, '/contact', 'both', 'public', 'header', true, 4);

-- Footer navigation (grouped by footer_group; group headings stay translation-driven)
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Products", "ar": "المنتجات", "ku": "بەرهەمەکان"}'::jsonb, '/products', 'both', 'public', 'footer', 'solutions', true, 0);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Plans", "ar": "الخطط", "ku": "پلانەکان"}'::jsonb, '/#plans', 'both', 'public', 'footer', 'solutions', true, 1);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "How It Works", "ar": "كيف يعمل", "ku": "چۆن کاردەکات"}'::jsonb, '/#how', 'both', 'public', 'footer', 'solutions', true, 2);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Contact", "ar": "تواصل معنا", "ku": "پەیوەندی"}'::jsonb, '/contact', 'both', 'public', 'footer', 'company', true, 0);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Sign in", "ar": "تسجيل الدخول", "ku": "چوونەژوورەوە"}'::jsonb, '/login', 'both', 'public', 'footer', 'company', true, 1);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Privacy Policy", "ar": "سياسة الخصوصية", "ku": "سیاسەتی تایبەتمەندی"}'::jsonb, '/privacy', 'both', 'public', 'footer', 'legal', true, 0);
insert into nav_menu_items (label, url, placement, access_rule, location, footer_group, visible, sort_order) values ('{"en": "Terms of Service", "ar": "شروط الخدمة", "ku": "مەرجەکانی خزمەتگوزاری"}'::jsonb, '/terms', 'both', 'public', 'footer', 'legal', true, 1);

-- Pricing display fields (setup fee, popular badge, per-plan CTA text)
update plans set setup_price_iqd = 75000, popular = false, cta = '{"en": "Get Started", "ar": "ابدأ الآن", "ku": "دەست پێبکە"}'::jsonb where id = 'vee_start';
update plans set setup_price_iqd = 150000, popular = true, cta = '{"en": "Choose Business", "ar": "اختر Business", "ku": "Business هەڵبژێرە"}'::jsonb where id = 'vee_business';
update plans set setup_price_iqd = 300000, popular = false, cta = '{"en": "Choose Pro", "ar": "اختر Pro", "ku": "Pro هەڵبژێرە"}'::jsonb where id = 'vee_pro';
update plans set setup_price_iqd = null, popular = false, cta = '{"en": "Talk to Vee", "ar": "تحدث مع Vee", "ku": "لەگەڵ Vee قسە بکە"}'::jsonb where id = 'vee_custom';

